version: "3.7"
services:

  redis:
    ports:
      - "6379:6379"
    image: redis:4-alpine
    command:
      - redis-server
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru

  rebrow:
    image: marian/rebrow
    ports:
      - 5001:5001
    links:
      - redis

  postgis:
    image: geographica/postgis:spry_sparrow
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres

volumes:
  db-data: